# Testing for pipeline python wrapper and scripts used inside rules
# Based on: https://github.com/marketplace/actions/setup-miniconda#example-1-basic-usage

name: Juno_cgmlst test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {os: macOS-latest}
          - {os: ubuntu-latest}
    name: Testing Juno_typing ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          environment-file: envs/juno_cgmlst.yaml
          channel-priority: flexible
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Test that the right schema is chosen for each sample.
        shell: bash -l {0}
        run: python ./tests/test_chewbbaca_per_genus.py
      - name: Test that the functions to download cgmlst schemes from different websites work.
        shell: bash -l {0}
        run: python ./tests/test_download_cgmlst_schemes.py
